### PR TITLE
fix initialization and three-request problem

### LINKED ISSUE #7: issue with three search requests on load
This is small issue I just noticed in both Open and OCW, basically on startup we fire off three search requests rather than just one.

The reason this is happening is because of how `useEffect` and `setState` interact.

- we set initial values for `text` and `activeFacets` at mount, by passing default values to `useState`.
- then we have a `useEffect` call that looks like this:
    ```js
    useEffect(() => {
      clearSearch()
      const { text, activeFacets } = deserializeSearchParams(window.location)
      setText(text)
      setActiveFacets(activeFacets)
      internalRunSearch(text, activeFacets)
      // dependencies intentionally left blank here, because this effect
      // needs to run only once - it's just to initialize the search state
      // based on the value of the URL (if any)
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [])
    ```
    this pulls the values (if any) from the search params in the URL bar and calls `setText` and `setActiveFacets`, which are both calls to the setState callbacks returned from `useState`. These calls trigger a re-render because that's what `setState` calls do.
- then we also have another `useEffect` call that looks like this:
    ```js
    useEffect(
      () => {
        internalRunSearch(text, activeFacets)
      },
      // eslint-disable-next-line react-hooks/exhaustive-deps
      [activeFacets]
    )
    ```
    this `useEffect` call basically is there to trigger a call to the search API whenever we change the facets, like clicking on one of them or clearing one or something.

The problem is baiscally how all these elements interact. When the component mounts, something like this is happening:

1. component mounts with default values for `text`, `activeFacets`
2. first render:
    1. first `useEffect` call fires, which calls `useState` causing a re-render and issues search request no. 1
    2. second `useEffect` call fires, which issues search request no. 2
4. second render:
    1. second `useEffect` call fires again because `activeFacets` has changed (by the `setState` call in `useEffect` no. 1). this triggers search request no. 3

whew!

The solution is to

1. set default values to values parsed for the URL bar from the get-go and remove setState calls from our 'on-startup' `useEffect` call (the first one above).
2. write a custom `useDidMountEffect` hook that skips the first render to use in place of the second `useEffect` call. we can do this safely because on mount our initial search request is handled by the other `useEffect` call.

### PR DESCRIPTION
**Pull request by aliceriot**
this closes #7 

I think the first thing is to read through the code here and the linked issue, to make sure it all makes sense. then if you want you can try out this branch in OCW or Open to make sure it fixes the issue.

1. first confirm that you see the three-request issue (as outlined in the issue) on Open and OCW.
2. check out this branch
3. run `npm pack`. this will produce a `.tgz` file that contains the same contents that will be uploaded to npm when this is published.
4. then you can install this `.tgz` file like a normal npm package by copying to the project directory in question and then using `yarn` with `./path/to/file.tgz` as the package name. Note that if you're running hugo-course-publisher natively (i.e. outside of docker) you will likely need to run `yarn cache clean` before you do this.

anyhow, after getting that to work you should be able to launch the search and the issue should be fixed.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -31,8 +32,14 @@ export const useCourseSearch = (
 ) => {
   const [incremental, setIncremental] = useState(false)
   const [from, setFrom] = useState(0)
-  const [text, setText] = useState("")
-  const [activeFacets, setActiveFacets] = useState(INITIAL_FACET_STATE)
+  const [text, setText] = useState(() => {
+    const { text } = deserializeSearchParams(window.location)
```
Comment (noisecapella) [inline src/index.js:36]: Hard to tell from the docs but this sets the initial state?

File: src/hooks.js [hunk 2]
```diff
@@ -0,0 +1,14 @@
+import { useEffect, useRef } from "react"
+
+export function useDidMountEffect(fn, deps) {
+  const renderedOnce = useRef(false)
```
Comment (noisecapella) [inline src/hooks.js:4]: Should this be `useState` or are you trying to store this boolean separately from the state?

Comment (aliceriot) [reply src/hooks.js:4]: it needs to not be `useState` because updating state triggers a re-render. `useRef` is the current 'escape hatch' that lets you just have a little state container you can write a value to without doing anything with the react lifecycle. It's not the best pattern, but the only real way to do what I'm trying to do here.

File: src/index.js (hunk 1 above)
Comment (aliceriot) [reply src/index.js:36]: yep, if you pass a function to `useState` the return value of that function will be the initial value held in the state container and then on subsequent calls it will just ignore the function.

**Review by noisecapella — APPROVED** [review]
Confirmed the issue on open and confirmed that this fixes it

File: src/hooks.js (hunk 2 above)
Comment (aliceriot) [reply src/hooks.js:4]: it's sort of the equivalent of putting a value directly on `this` if you're writing a react component with an ES6 class
